apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: github-art-tekton
  janus-idp.io/tekton: github-art-tekton
  backstage.io/kubernetes-id: github-art-tekton
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: github-art-tekton
resources:
- deployment.yaml
- route.yaml
- service.yaml
